"""Batch automation contracts, typed models, validation, metadata registry, and execution bindings."""

from __future__ import annotations

from batch.allocation import (
    AllocatedBatchFile,
    AllocatedBatchFormat,
    AllocatedBatchWork,
    BatchAllocationCollisionError,
    BatchSafetyBoundary,
    BatchSafetyRejectionError,
    PreparedBatchFile,
    PreparedBatchFormat,
    PreparedBatchWork,
    allocate_batch_work,
    build_collision_rejection,
    validate_prepared_work_consistency,
)
from batch.bindings import (
    BatchHandlerFactory,
    BatchOperationHandler,
    OperationBinding,
    OperationBindings,
)
from batch.execution import (
    BatchExecutionOutcome,
    BatchExecutionSpec,
    BatchItemContext,
    BatchItemOutcome,
    BatchProgressPhase,
    BatchProgressUpdate,
)
from batch.models import (
    BatchArtifactRecord,
    BatchConfigurationError,
    BatchContractError,
    BatchDiagnostic,
    BatchFileResult,
    BatchInputSelection,
    BatchManifest,
    BatchManifestReference,
    BatchMetadata,
    BatchOperation,
    BatchOperationType,
    BatchOptions,
    BatchRequest,
    BatchResponse,
    BatchSummary,
    BatchValidationError,
    FileResultStatus,
    ManifestArtifactRecord,
    ManifestFileResult,
)
from batch.registry import (
    OperationDescriptor,
    OperationRegistry,
    build_initial_registry,
)
from batch.service import BatchService

__all__: list[str] = [
    "AllocatedBatchFile",
    "AllocatedBatchFormat",
    "AllocatedBatchWork",
    "BatchAllocationCollisionError",
    "BatchArtifactRecord",
    "BatchConfigurationError",
    "BatchContractError",
    "BatchDiagnostic",
    "BatchExecutionOutcome",
    "BatchExecutionSpec",
    "BatchFileResult",
    "BatchHandlerFactory",
    "BatchInputSelection",
    "BatchItemContext",
    "BatchItemOutcome",
    "BatchManifest",
    "BatchManifestReference",
    "BatchMetadata",
    "BatchOperation",
    "BatchOperationHandler",
    "BatchOperationType",
    "BatchOptions",
    "BatchProgressPhase",
    "BatchProgressUpdate",
    "BatchRequest",
    "BatchResponse",
    "BatchSafetyBoundary",
    "BatchSafetyRejectionError",
    "BatchService",
    "BatchSummary",
    "BatchValidationError",
    "FileResultStatus",
    "ManifestArtifactRecord",
    "ManifestFileResult",
    "OperationBinding",
    "OperationBindings",
    "OperationDescriptor",
    "OperationRegistry",
    "PreparedBatchFile",
    "PreparedBatchFormat",
    "PreparedBatchWork",
    "allocate_batch_work",
    "build_collision_rejection",
    "build_initial_registry",
    "validate_prepared_work_consistency",
]
