"""Run manifest subsystem for CAD Copilot.

Provides canonical schema validation, stable ID indexing, deterministic
FeaturePlan serialization, execution metrics tracking, and manifest staging/publication.
"""

from __future__ import annotations

from manifests.models import (
    ARTIFACT_FORMAT_TO_TYPE,
    CANONICAL_CAD_RUNTIME_PRODUCT,
    CANONICAL_CONTRACT_VERSION,
    CANONICAL_ENGINE_NAME,
    CANONICAL_MANIFEST_VERSION,
    CANONICAL_UNIT,
    FREE_TEXT_CREDENTIAL_PATTERN,
    IDENTIFIER_PATTERN,
    LOCAL_PATH_PATTERN,
    REQUEST_ID_PATTERN,
    SENSITIVE_KEY_PATTERN,
    SHA256_HEX_PATTERN,
    ManifestArtifactRecord,
    ManifestConfigurationError,
    ManifestError,
    ManifestExecution,
    ManifestInspection,
    ManifestOperationResult,
    ManifestStableIds,
    ManifestValidationError,
    PreparedManifestData,
    RunManifestContext,
    resolve_engine_version,
)
from manifests.plan_codec import (
    MAX_MANIFEST_DEFAULTS,
    MAX_MANIFEST_DIAGNOSTICS,
    compute_plan_fingerprint,
    extract_manifest_stable_ids,
    generate_structural_design_intent,
    harden_plan_metadata,
    prepare_manifest_data,
    project_manifest_defaults,
    project_manifest_diagnostics,
    serialize_canonical_feature_plan,
    validate_identifier,
    validate_serialized_feature_plan,
)
from manifests.run_manifest import (
    CANONICAL_ARTIFACT_SPECS,
    SCHEMA_RESOURCE_NAME,
    assemble_run_manifest,
    compute_prompt_fingerprint,
    get_run_manifest_validator,
    load_run_manifest_schema,
    write_staged_run_manifest,
)

__all__ = [
    "ARTIFACT_FORMAT_TO_TYPE",
    "CANONICAL_ARTIFACT_SPECS",
    "CANONICAL_CAD_RUNTIME_PRODUCT",
    "CANONICAL_CONTRACT_VERSION",
    "CANONICAL_ENGINE_NAME",
    "CANONICAL_MANIFEST_VERSION",
    "CANONICAL_UNIT",
    "FREE_TEXT_CREDENTIAL_PATTERN",
    "IDENTIFIER_PATTERN",
    "LOCAL_PATH_PATTERN",
    "MAX_MANIFEST_DEFAULTS",
    "MAX_MANIFEST_DIAGNOSTICS",
    "REQUEST_ID_PATTERN",
    "SCHEMA_RESOURCE_NAME",
    "SENSITIVE_KEY_PATTERN",
    "SHA256_HEX_PATTERN",
    "ManifestArtifactRecord",
    "ManifestConfigurationError",
    "ManifestError",
    "ManifestExecution",
    "ManifestInspection",
    "ManifestOperationResult",
    "ManifestStableIds",
    "ManifestValidationError",
    "PreparedManifestData",
    "RunManifestContext",
    "assemble_run_manifest",
    "compute_plan_fingerprint",
    "compute_prompt_fingerprint",
    "extract_manifest_stable_ids",
    "generate_structural_design_intent",
    "get_run_manifest_validator",
    "harden_plan_metadata",
    "load_run_manifest_schema",
    "prepare_manifest_data",
    "project_manifest_defaults",
    "project_manifest_diagnostics",
    "resolve_engine_version",
    "serialize_canonical_feature_plan",
    "validate_identifier",
    "validate_serialized_feature_plan",
    "write_staged_run_manifest",
]
