use std::io::Read;
use std::os::windows::fs::MetadataExt;
use std::path::Path;

use image::ImageDecoder;
use sha2::{Digest, Sha256};

use super::output::verify_folder_containment;
use super::types::CommandError;

pub const MAX_PREVIEW_BYTES: u64 = 20_000_000; // 20 MB cap
pub const MAX_AXIS_PIXELS: u32 = 8_192; // 8,192 px max per axis
pub const MAX_DECLARED_PIXELS: u64 = 32_000_000; // 32 million declared pixels
const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x0400;

pub fn load_preview_jpeg(
    selected_output_root: &Path,
    request_id: &str,
    expected_sha256: Option<&str>,
    expected_root_identity: Option<super::output::FileSystemIdentity>,
) -> Result<Vec<u8>, CommandError> {
    let binding =
        verify_folder_containment(selected_output_root, request_id, expected_root_identity)?;
    let canonical_run = &binding.canonical_run;

    // Look strictly for canonical {request_id}.jpg generated by engine
    let preview_path = canonical_run.join(format!("{}.jpg", request_id));
    if !preview_path.exists() {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            "Preview image file was not found in the run folder.",
        ));
    }

    let sym_meta = std::fs::symlink_metadata(&preview_path).map_err(|e| {
        CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            format!("Failed to read preview metadata: {}", e),
        )
    })?;

    if sym_meta.is_symlink() || (sym_meta.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT) != 0 {
        return Err(CommandError::new(
            "OUTPUT_PATH_NOT_ALLOWED",
            "Preview image is a symlink or reparse point.",
        ));
    }

    if let Ok(canon_preview) = preview_path.canonicalize() {
        if !canon_preview.starts_with(canonical_run) {
            return Err(CommandError::new(
                "OUTPUT_PATH_NOT_ALLOWED",
                "Preview image path escapes the run directory.",
            ));
        }
    }

    let file = std::fs::File::open(&preview_path).map_err(|e| {
        CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            format!("Failed to open preview image: {}", e),
        )
    })?;

    binding.verify_file(&file)?;

    let meta = file.metadata().map_err(|e| {
        CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            format!("Failed to read preview metadata: {}", e),
        )
    })?;

    if meta.is_symlink() || (meta.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT) != 0 {
        return Err(CommandError::new(
            "OUTPUT_PATH_NOT_ALLOWED",
            "Preview image is a symlink or reparse point.",
        ));
    }

    if !meta.is_file() {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            "Preview image is not a regular file.",
        ));
    }

    if meta.len() > MAX_PREVIEW_BYTES {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            format!(
                "Preview image ({} bytes) exceeds maximum permitted limit of 20 MB.",
                meta.len()
            ),
        ));
    }

    let mut bytes = Vec::with_capacity(std::cmp::min(meta.len(), MAX_PREVIEW_BYTES) as usize);
    file.take(MAX_PREVIEW_BYTES + 1)
        .read_to_end(&mut bytes)
        .map_err(|e| {
            CommandError::new(
                "RESULT_ACCESS_UNAVAILABLE",
                format!("Failed to read preview image: {}", e),
            )
        })?;

    if bytes.len() as u64 > MAX_PREVIEW_BYTES {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            "Preview image exceeded maximum permitted limit of 20 MB during read.",
        ));
    }

    if bytes.len() < 4 || bytes[0] != 0xFF || bytes[1] != 0xD8 {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            "Preview file does not start with a valid JPEG SOI marker.",
        ));
    }

    if let Some(expected_digest) = expected_sha256 {
        let mut hasher = Sha256::new();
        hasher.update(&bytes);
        let actual_digest = format!("{:02x}", hasher.finalize());
        if !actual_digest.eq_ignore_ascii_case(expected_digest) {
            return Err(CommandError::new(
                "RESULT_ACCESS_UNAVAILABLE",
                format!(
                    "Preview image digest mismatch: expected '{}', computed '{}'.",
                    expected_digest, actual_digest
                ),
            ));
        }
    }

    let cursor = std::io::Cursor::new(&bytes);
    let decoder = image::codecs::jpeg::JpegDecoder::new(cursor).map_err(|e| {
        CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            format!("Failed to parse JPEG headers: {}", e),
        )
    })?;

    let (width, height) = decoder.dimensions();
    if width == 0 || height == 0 {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            "Preview image has invalid zero dimensions.",
        ));
    }

    if width > MAX_AXIS_PIXELS || height > MAX_AXIS_PIXELS {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            format!(
                "Preview JPEG dimensions ({}x{}) exceed maximum permitted {} pixels per axis.",
                width, height, MAX_AXIS_PIXELS
            ),
        ));
    }

    let total_pixels = (width as u64).saturating_mul(height as u64);
    if total_pixels > MAX_DECLARED_PIXELS {
        return Err(CommandError::new(
            "RESULT_ACCESS_UNAVAILABLE",
            format!(
                "Preview JPEG total declared pixels ({}) exceed maximum permitted limit of 32 million pixels.",
                total_pixels
            ),
        ));
    }

    Ok(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::File;
    use std::io::Write;
    use std::path::PathBuf;

    struct TestDir(PathBuf);
    impl TestDir {
        fn new(prefix: &str) -> Self {
            let nanos = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let path = std::env::temp_dir().join(format!("cad_test_prev_{}_{}", prefix, nanos));
            std::fs::create_dir_all(&path).unwrap();
            Self(path)
        }
        fn path(&self) -> &Path {
            &self.0
        }
    }
    impl Drop for TestDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    fn setup_preview_test(test_name: &str) -> (TestDir, PathBuf, String) {
        let temp = TestDir::new(test_name);
        let request_id = format!("req_{}", test_name);
        let run_dir = temp.path().join(&request_id);
        std::fs::create_dir_all(&run_dir).expect("Failed to create run dir");
        (temp, run_dir, request_id)
    }

    // Minimal 1x1 valid JPEG byte sequence
    fn create_valid_1x1_jpeg() -> Vec<u8> {
        vec![
            0xFF, 0xD8, // SOI
            0xFF, 0xE0, 0x00, 0x10, b'J', b'F', b'I', b'F', 0x00, 0x01, 0x01, 0x01, 0x00, 0x48,
            0x00, 0x48, 0x00, 0x00, // APP0
            0xFF, 0xDB, 0x00, 0x43, 0x00, // DQT
            // 64 bytes quantization table
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 0xFF, 0xC0, 0x00, 0x0B, 0x08, 0x00, 0x01, 0x00, 0x01, 0x01, 0x01,
            0x11, 0x00, // SOF0 (1x1, 1 component)
            0xFF, 0xC4, 0x00, 0x1F, 0x00, // DHT DC
            0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B,
            0xFF, 0xDA, 0x00, 0x08, 0x01, 0x01, 0x00, 0x00, 0x3F, 0x00, // SOS
            0x7B, 0x40, // compressed image data
            0xFF, 0xD9, // EOI
        ]
    }

    #[test]
    fn test_load_preview_jpeg_valid_1x1() {
        let (temp, run_dir, request_id) = setup_preview_test("valid_preview");
        let jpeg_bytes = create_valid_1x1_jpeg();
        let preview_path = run_dir.join(format!("{}.jpg", request_id));
        let mut file = File::create(&preview_path).unwrap();
        file.write_all(&jpeg_bytes).unwrap();

        let loaded = load_preview_jpeg(temp.path(), &request_id, None, None)
            .expect("Should load valid preview");
        assert_eq!(loaded, jpeg_bytes);
    }

    #[test]
    fn test_load_preview_jpeg_missing_fails() {
        let (temp, _run_dir, request_id) = setup_preview_test("missing_preview");
        let err = load_preview_jpeg(temp.path(), &request_id, None, None).unwrap_err();
        assert_eq!(err.code, "RESULT_ACCESS_UNAVAILABLE");
        assert!(err.message.contains("Preview image file was not found"));
    }

    #[test]
    fn test_load_preview_jpeg_non_jpeg_magic_fails() {
        let (temp, run_dir, request_id) = setup_preview_test("non_jpeg");
        let preview_path = run_dir.join(format!("{}.jpg", request_id));
        let mut file = File::create(&preview_path).unwrap();
        file.write_all(b"NOT_A_JPEG_FILE").unwrap();

        let err = load_preview_jpeg(temp.path(), &request_id, None, None).unwrap_err();
        assert_eq!(err.code, "RESULT_ACCESS_UNAVAILABLE");
        assert!(err.message.contains("valid JPEG SOI marker"));
    }

    #[test]
    fn test_load_preview_jpeg_oversized_fails() {
        let (temp, run_dir, request_id) = setup_preview_test("oversized_preview");
        let preview_path = run_dir.join(format!("{}.jpg", request_id));
        let file = File::create(&preview_path).unwrap();
        file.set_len(MAX_PREVIEW_BYTES + 1).unwrap();

        let err = load_preview_jpeg(temp.path(), &request_id, None, None).unwrap_err();
        assert_eq!(err.code, "RESULT_ACCESS_UNAVAILABLE");
        assert!(err.message.contains("exceeds maximum permitted limit"));
    }

    #[test]
    fn test_load_preview_jpeg_identity_mismatch_fails() {
        let (temp, run_dir, request_id) = setup_preview_test("id_mismatch");
        let jpeg_bytes = create_valid_1x1_jpeg();
        let preview_path = run_dir.join(format!("{}.jpg", request_id));
        let mut file = File::create(&preview_path).unwrap();
        file.write_all(&jpeg_bytes).unwrap();

        let fake_identity = super::super::output::FileSystemIdentity {
            volume_serial_number: 999999,
            file_index: 888888,
        };
        let err =
            load_preview_jpeg(temp.path(), &request_id, None, Some(fake_identity)).unwrap_err();
        assert_eq!(err.code, "OUTPUT_PATH_NOT_ALLOWED");
        assert!(err.message.contains("filesystem identity"));
    }
}
