"""Pure domain geometry math, SO(3) coordinate transforms, and AST models for CAD Copilot.

Invariants:
    - Zero I/O Purity (NFR-1): 100% computational domain logic with zero COM/CAD imports.
    - Mathematical Determinism (NFR-2): SO(3) coordinate frames and exact polygon math.
    - Strict Static Typing (NFR-4): 100% annotated with explicit __all__ exports.
"""

from __future__ import annotations

from geometry.face_context import (
    FaceContext,
    resolve_face_context,
)
from geometry.gate_policy import (
    GatePolicyMode,
    current_gate_policy_mode,
    relaxed_gate_warning,
    shadow_gate_warning,
    should_retry_canonical_rejection,
)
from geometry.gear_math import (
    gear_base_radius,
    gear_pitch_radius,
    gear_root_radius,
    gear_tip_radius,
    involute_point,
    spur_gear_outline_points,
    spur_gear_profile_points,
    validate_gear_parameters,
)
from geometry.plan_geometry import (
    Point2DLike,
    SubtractiveProfileFeature,
    bounding_boxes_overlap,
    is_polygon_ccw,
    point_in_polygon,
    point_to_segment_distance,
    polygon_area,
    polygon_bounding_box,
    polygon_centroid,
    polygon_signed_area,
)
from geometry.plan_models import (
    CANONICAL_PLAN_VERSION,
    DEFAULT_EDGE_MARGIN_MM,
    ArtifactPolicy,
    BodyPlacement,
    BooleanOperation,
    BooleanOperationFamily,
    CircularThroughHoleFeature,
    CylinderBaseBody,
    DefaultApplied,
    FeaturePlan,
    FeaturePlanBackendPortRun,
    FeaturePlanBaseBody,
    FeaturePlanFeature,
    FeaturePlanStatus,
    FeaturePlanValidationError,
    LoweringStrategy,
    PartMetadata,
    PlacementMode,
    ProfileCutoutFeature,
    ProfilePoint2D,
    RectangularBaseBody,
    RectangularExtrudedPadFeature,
    RectangularThroughCutoutFeature,
    RevolvedProfileFeature,
    RevolvedShaftBaseBody,
    SlotOrientationAxis,
    SlotThroughCutoutFeature,
    SphereBaseBody,
    SpurGearBaseBody,
    SweepCrossSectionSpec,
    SweepPathSpec,
    SweptProtrusionFeature,
    Units,
    UnsupportedFeature,
    ValidationDiagnostic,
)
from geometry.plan_parser import (
    MAX_BOOLEAN_OPERATIONS,
    MAX_FEATURES,
    MAX_PRIMITIVE_BODIES,
    MAX_PROFILE_POINTS,
    feature_plan_from_dict,
)
from geometry.plan_validation import (
    validate_feature_plan,
)

__all__ = [
    "CANONICAL_PLAN_VERSION",
    "DEFAULT_EDGE_MARGIN_MM",
    "MAX_BOOLEAN_OPERATIONS",
    "MAX_FEATURES",
    "MAX_PRIMITIVE_BODIES",
    "MAX_PROFILE_POINTS",
    "ArtifactPolicy",
    "BodyPlacement",
    "BooleanOperation",
    "BooleanOperationFamily",
    "CircularThroughHoleFeature",
    "CylinderBaseBody",
    "DefaultApplied",
    "FaceContext",
    "FeaturePlan",
    "FeaturePlanBackendPortRun",
    "FeaturePlanBaseBody",
    "FeaturePlanFeature",
    "FeaturePlanStatus",
    "FeaturePlanValidationError",
    "GatePolicyMode",
    "LoweringStrategy",
    "PartMetadata",
    "PlacementMode",
    "Point2DLike",
    "ProfileCutoutFeature",
    "ProfilePoint2D",
    "RectangularBaseBody",
    "RectangularExtrudedPadFeature",
    "RectangularThroughCutoutFeature",
    "RevolvedProfileFeature",
    "RevolvedShaftBaseBody",
    "SlotOrientationAxis",
    "SlotThroughCutoutFeature",
    "SphereBaseBody",
    "SpurGearBaseBody",
    "SubtractiveProfileFeature",
    "SweepCrossSectionSpec",
    "SweepPathSpec",
    "SweptProtrusionFeature",
    "Units",
    "UnsupportedFeature",
    "ValidationDiagnostic",
    "bounding_boxes_overlap",
    "current_gate_policy_mode",
    "feature_plan_from_dict",
    "gear_base_radius",
    "gear_pitch_radius",
    "gear_root_radius",
    "gear_tip_radius",
    "involute_point",
    "is_polygon_ccw",
    "point_in_polygon",
    "point_to_segment_distance",
    "polygon_area",
    "polygon_bounding_box",
    "polygon_centroid",
    "polygon_signed_area",
    "relaxed_gate_warning",
    "resolve_face_context",
    "shadow_gate_warning",
    "should_retry_canonical_rejection",
    "spur_gear_outline_points",
    "spur_gear_profile_points",
    "validate_feature_plan",
    "validate_gear_parameters",
]
